name: DevSecOps Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch: # This line enables manual trigger

jobs:
  code-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Bandit Security Scan
        uses: pycqa/bandit-action@main
        with:
          path: src/
          level: high

      - name: Upload Bandit Report
        uses: actions/upload-artifact@v3
        with:
          name: Bandit_Report
          path: results.sarif

  secrets-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run TruffleHog Secret Scan
        uses: trufflesecurity/trufflehog@main
        with:
          path: src/

  docker-build:
    runs-on: ubuntu-latest
    needs: [code-analysis, secrets-scan]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t my-devsecops-app:latest .
