name: DevSecOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  code-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Security Code Analysis
        uses: PyCQA/bandit-action@v1.7.4
        with:
          path: src/
          level: high

  secrets-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Secrets Scan
        uses: trufflesecurity/trufflehog@v3
        with:
          path: src/

  docker-build:
    runs-on: ubuntu-latest
    needs: [code-analysis, secrets-scan]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t my-devsecops-app:latest .
